### PR TITLE
fix keyboard accessibility for speed selector

### PR DESCRIPTION
**Pull request by simonista**
at some point this was removed in the build version of the css, but not
in the src version, so the change got reverted.

### CODE REVIEW

**Comment by benternet** [comment]
@simonista we have a history of updating the build files in the PR that contains the src file changes as well. mind updating with those?

**Review by a-b-r-o-w-n — COMMENTED** [review]
Looks good. just waiting for an updated build.

**Comment by benternet** [comment]
i was going back to see what the original issue was that was fixed in the build version, but it looks like this change never was applied there? ie the last change i can see on that line in the build file is from 2 years ago and that was to change from `visibility: hidden` to `display: none`: https://github.com/instructure/mediaelement/commit/3e4fdd92c6e6acda20cdc864655cc498b599040a#diff-099b54c5c035e257619db4656fd4111eR905

@simonista would you mind putting a little bit more info in the commit message about what was broken and therefor fixed with this commit?

**Comment by simonista** [comment]
@benternet I updated the commit message with more detail.  I'll update the build files once the other PR is merged, so I don't have to deal with conflicts.

**Comment by benternet** [comment]
ah weird, this was initially removed with https://github.com/instructure/mediaelement/commit/f1ecd4f94d76d9daccb05db2f54b0d352fbe6ada#diff-e5b02417e93f209b15326312d2a39577 basically i'm looking back in to the history for this change because i'm worried that other things unknowingly got reverted somehow.

**Comment by simonista** [comment]
@benternet That commit doesn't show up when I run `git log -- src/css/mediaelementplayer.css` on master...

**Comment by simonista** [comment]
so maybe we need to bring back that whole commit?  I'm not sure, I'm SUPER confused by this git history :(

**Comment by benternet** [comment]
ummmm yea i'm super confused too. this definitely was merged to master in https://github.com/instructure/mediaelement/pull/8 so i'm worried we might also be missing some other stuff we don't know about.

**Comment by benternet** [comment]
somehow between our 2.38.0 and 2.39.0 it looks like all of that commit got reverted

**Comment by benternet** [comment]
oooo it was our merge of the latest public v2 - https://github.com/instructure/mediaelement/pull/23

**Comment by simonista** [comment]
Good find.  From a quick look at the diff, it looks like the css changes were reverted but not the js changes.  Do you want me to look into re-applying all the css changes from f1ecd4f94d76d9daccb05db2f54b0d352fbe6ada?

**Comment by benternet** [comment]
yes plz @simonista. i'll also see if i can find out any other commits that may have been lost during that rebase.

**Comment by benternet** [comment]
@simonista do you have any updates here?

**Comment by simonista** [comment]
Sorry, I'll try to push it later today.  Been focused on something else.

**Comment by simonista** [comment]
Okay @benternet, updates pushed.

**Review by benternet — APPROVED** [review]

**Review by kyler-instructure — APPROVED** [review]
QA +1

**Pull request merged**
