### PR TITLE
safe text and attribute insertions of player title, refs ARC-3203

### PR DESCRIPTION
**Pull request by mziwisky**
this closes up an XSS vector.  previously, passing a titleText of, e.g.,
"``" would insert the img tag
into the DOM.

### CODE REVIEW

**Review by a-b-r-o-w-n — COMMENTED** [review]
How does this change fix the xss vulnerability? I initially thought that jquery was sanitizing the text, but the documentation suggests that `html` accepts an html string.

**Comment by mziwisky** [comment]
where we had been doing string concatenation of the raw user input, we're now using jquery methods `.text()` and `.attr()` to set the values safely.

**Comment by a-b-r-o-w-n** [comment]
Yeah, I see that. I'm just asking how that is different that using the raw string in the case of the `html` call?

EDIT: for some reason I was thinking you had used `#html` instead of `#text`. Carry on! 🤦‍♂️

**Review by a-b-r-o-w-n — APPROVED** [review]

**Comment by bensolo-inst** [comment]
Verified as fixed using the original repro steps/scenario.  Also, no regressions observed.

**Pull request merged**
