### PR TITLE
sanitize html outside of active DOM, fixes ARC-2690

### PR DESCRIPTION
**Pull request by benternet**
mounting the given HTML in an element in the active DOM was actually
causing the browser to execute that new tree. this allowed for
injection attacks such as:

``

even though that element would have been removed after mounting.

instead let’s just parse and sanitize the html outside of the active
DOM.

### CODE REVIEW

**Comment by benternet** [comment]
looks like we should be OK to use this - https://caniuse.com/#feat=xml-serializer

**Review by a-b-r-o-w-n — APPROVED** [review]
This is nifty. Good work.

**Review by mziwisky — APPROVED** [review]
I concur, quite nifty

**Comment by bensolo-inst** [comment]
Verified this fix works as expected (blocking disallowed tags, whitelisting allowed tags in captions).  Also verified that Chrome, Firefox, Safari, and Edge playback with captions continues to work as expected. (No issues observed.)

**Pull request merged**
